# Generated by Django 4.1 on 2022-09-20 18:52

import ApiImagenesApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='./marcos', validators=[ApiImagenesApp.models.Marco.validate_image])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ApiImagenesApp.evento')),
            ],
            options={
                'verbose_name': 'Marco',
                'verbose_name_plural': 'Marcos',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ApiImagenesApp.marco')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('identificacion', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.AddField(
            model_name='marco',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiImagenesApp.persona'),
        ),
    ]
