# Generated by Django 4.1 on 2022-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiImagenesApp', '0003_alter_marco_personaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marco',
            name='imagen',
            field=models.ImageField(upload_to='./media/marcos'),
        ),
    ]
