# Generated by Django 4.1 on 2022-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiImagenesApp', '0004_alter_marco_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marco',
            options={'verbose_name': 'Marco', 'verbose_name_plural': 'Marcos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.RenameField(
            model_name='marco',
            old_name='personaID',
            new_name='persona',
        ),
        migrations.AlterField(
            model_name='marco',
            name='imagen',
            field=models.ImageField(upload_to='./marcos'),
        ),
    ]
